### ISSUE TITLE
The variable CMAKE_CXX_STANDARD is invalid on osx with cmake 3.1.2

### ISSUE THREAD

**Issue by micooz** [avplayer/avhtml#2]
And this bug was fixed in cmake 3.2:

http://www.cmake.org/Bug/view.php?id=15355

To fix it:
- avoid supporting to osx with cmake 3.1
- set cmake_minimum_required(VERSION 3.2)
- use set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11") instead of CMAKE_CXX_STANDARD

**Comment by microcai** [comment]
cmake 3.2 is not released yet. since this bug is fixed upstream, I will not workarround already fixed bug.
I'll use cmake_minimum_required(VERSION 3.2) as soon as cmake 3.2 is offically released.

**Comment by microcai** [comment]
re open for track.
