### ISSUE TITLE
Link error when building html5test by clang.

### ISSUE THREAD

**Issue by Micooz** [avplayer/avhtml#3]
There is no problem to build `html5` library, but when linking it to `html5test` some error occurred.

clang cannot find some template function symbols(build_matchers,append_partial_html,basic_charset.etc.), because they are implemented in the separated file(html5.cpp).

According to the recommendation of Google Coding Style(C++), template functions should be declared and implemented in the same file, usually in the `.hpp` file(you can include a `impl` file after function declarations, like boost library do.)

**Comment by microcai** [comment]
I'm sorry, I don't get a mac to test with.

**Comment by microcai** [comment]
fixed
